game/urls.py
from django.urls import path
from django.contrib.auth.decorators import user_passes_test

from django.views.generic.base import RedirectView

from game.views import *

app_name = 'game'

urlpatterns = [
    path('', RedirectView.as_view(url='status', permanent=False)),
    
    path('status/', VillageStatusView.as_view(), name='status'),
    path('announcements/', AnnouncementsListView.as_view(), name='announcements'),
    
    path('usepower/', UsePowerView.as_view(), name='usepower'),
    path('vote/', VoteView.as_view(), name='vote'),
    path('elect/', ElectView.as_view(), name='elect'),
    path('personalinfo/', PersonalInfoView.as_view(), name='personalinfo'),
    path('appoint/', AppointView.as_view(), name='appoint'),
    path('comment/', CommentView.as_view(), name='comment'),

    path('join/', JoinGameView.as_view(), name='join'), # Aggiunge il giocatore
    path('leave/', LeaveGameView.as_view(), name='leave'), # Rimuove il giocatore
    path('newplayer/', NewPlayerView.as_view(), name='newplayer'), # Crea un nuovo utente e lo aggiunge alla partita

    path('as_gm/', as_gm, name='as_gm'), # Assume i poteri da GM
    path('as_normal_user/', as_normal_user, name='as_normal_user'), # Lascia i poteri da GM

    path('managemasters/', ManageGameMastersView.as_view(), name='managemasters'), # Aggiunge un master alla partita
    path('deletemaster/<int:pk>', DeleteGameMasterView.as_view(), name='deletemaster'), # Toglie un master dalla partita
    path('publishannouncement/', PublishAnnouncementView.as_view(), name='publishannouncement'), # Pubblica un annuncio
    path('deleteannouncement/<int:pk>', DeleteAnnouncementView.as_view(), name='deleteannouncement'), # Cancella un annuncio
    path('setup/', SetupGameView.as_view(), name='setup'), # Prepara l'inizio
    path('seed/', SeedView.as_view(), name='seed'), # Cambia o crea il seed
    path('composition/', VillageCompositionView.as_view(), name='composition'), # Imposta la composizione del villaggio
    path('spectralsequence/', SpectralSequenceView.as_view(), name='spectralsequence'), # Imposta la successione spettrale
    path('propositions/', InitialPropositionsView.as_view(), name='propositions'), # Pubblica le proposizioni iniziali
    path('deleteproposition/<int:pk>/', DeletePropositionView.as_view(), name='deleteproposition'), # Cancella una proposizione iniziale
    path('soothsayer/<int:pk>/', SoothsayerView.as_view(), name='soothsayer'), # Cambia le frasi dei divinatori
    path('deletesoothsayer/<int:pk>/', DeleteSoothsayerView.as_view(), name='deletesoothsayer'), # Cancella una proposizione per il divinatore
    path('settings/', GameSettingsView.as_view(), name='settings'), # Cambia le impostazioni della partita

    path('rollbackturn/', RollbackLastTurnView.as_view(), name='rollbackturn'), # Riporta la partita alla fine del turno precedente, cancellando gli eventi di quello in corso.
    path('restart/', RestartGameView.as_view(), name='restart'), # Elimina tutti gli eventi e riapre le iscrizioni
    path('load/', LoadGameView.as_view(), name='load'), # Elimina tutti gli eventi e carica da file
    
    path('delete/', not_implemented, name='delete'), # Cancella la partita
    
    path('adminstatus/', AdminStatusView.as_view(), name='adminstatus'),
    path('advanceturn/', AdvanceTurnView.as_view(), name='advanceturn'),
    path('forcevictory/', ForceVictoryView.as_view(), name='forcevictory'),
    path('pointofview/', PointOfView.as_view(), name='pointofview'),
    path('dump/', DumpView.as_view(), name='dump'),
]

lupus/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

from django.views.generic.base import RedirectView
#from django.core.urlresolvers import reverse_lazy
from game import views
from game.views import *


admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('index/', HomeView.as_view(), name='home'),
    path('', RedirectView.as_view(pattern_name='home', permanent=False)),
    path('ruleset/', RulesetView.as_view(), name='ruleset'),
    path('credits/', CreditsView.as_view(), name='credits'),
    path('trailer/', TrailerView.as_view(), name='trailer'),
    path('prototypes/', PrototypesView.as_view(), name='prototypes'),
    path('error/', ErrorView.as_view(), name='error'),

    path('creategame/', CreateGameView.as_view(), name='creategame'),

    path('game/<str:game_name>/', include('game.urls', namespace='game'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

templates/action_elect.html
{% extends "base.html" %}

{% block content %}
    <h1>Elezione del Sindaco</h1>
    
    <form action="{% url 'elect' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
{% endblock %}

templates/command.html
{% extends "base.html" %}

{% block content %}
<main id="content">
    <h1>{{ title }}</h1>

    <div class="info-block">
        <form action="{% url url_name game_name=game.name%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <script type="text/javascript">$('#id_multiple_role_class').multiSelect({
            selectableOptgroup: true,
            selectableHeader: "<div class='custom-header'>Ruoli disponibili</div>",
            selectionHeader: "<div class='custom-header'>Ruoli selezionati</div>"
        })</script>
        <p><input type="submit" value="Invia" /></p>
        </form>
    </div>
</main>
{% endblock %}

templates/command_submitted.html
{% extends "base.html" %}

{% block content %}
<main id="content">
    <h1>{{ title }}</h1>
    <div class="info-block">
    <p><strong>L'azione è stata registrata con successo.</strong></p>
    </div>
</main>
{% endblock %}

templates/create_game.html
{% extends "base.html" %}

{% block content %}

<main id="content">
    <h1>Crea nuova partita</h1>

    <div class="info-block">
        <p>
        <form action="{% url 'creategame' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Crea partita" /></p>
        </form>
        </p>

        {% if message != None %}
            <p><strong>{{ message }}</strong></p>
        {% endif %}

    </div>
</main>
{% endblock %}

templates/credits.html
{% extends "base.html" %}

{% block content %}

<main id="content">
    <h1>Riconoscimenti</h1>

    <div class="info-block">

        <table class="normal">
        <tr><td>Game Master</td><td>Giovanni Mascellani, Alessandro Iraci, Giovanni Paolini, Manuele Cusumano, Matteo Migliorini</td></tr>
        <tr><td>Organizzazione</td><td>Giovanni Paolini, Giovanni Mascellani, Alessandro Iraci, Leonardo Tolomeo</td></tr>
        <tr><td>Server web</td><td>Giovanni Mascellani, Giovanni Paolini, Matteo Migliorini</td></tr>
        <tr><td>Grafica</td><td>Alessandro Achille, Flavio Ascari</td></tr>

        <tr><td>Regolamento</td><td>Luca Ghidelli, Alessandro Iraci, Giovanni Mascellani, Giovanni Paolini, Leonardo Tolomeo</td></tr>
        <tr><td>Ambientazione</td><td>Alessandro Iraci, Marta Mussi, Giovanni Paolini, Leonardo Tolomeo</td></tr>

        <tr><td>Contributi da edizioni precedenti</td><td>Andrea Caleo, Francesco Guatieri, Chiara Strazzulla</td></tr>
        </table>

    </div>
</main>

{% endblock %}

templates/error.html
{% extends "base.html" %}

{% block content %}

<main id="content">

    <h1>Errore</h1>

    <div class="info-block">
    <p>C'è stato un errore interno del server. Se vedi questa pagina, contatta immediatamente i Game Master.</p>

    <p>Il problema verrà risolto il prima possibile.</p>
    </div>

</main>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<main id="content">

    <h1>Home</h1>

    <div class="info-block">
    <p>
    <i>Lupus in tempo reale</i> è una variante dei più tradizionali Lupus in Tabula e Mafia, caratterizzata da un maggiore
    coinvolgimento e da interazioni più sofisticate tra i giocatori. La principale differenza consiste nel ritmo del
    gioco: la partita si estende infatti su diversi giorni, in modo aderente all'ambientazione. Sono premiate dalla
    dinamica di gioco la logica, la capacità di bluffare (e di smascherare i bluff altrui), la capacità di saper coordinare
    un'azione di gruppo, il carisma e le velleità leaderistiche.
    </p>

    <p>
    <i>Lupus in tempo reale</i> è stato inventato nel 2010, ed è stato giocato una volta all'anno fino al 2012 sotto la supervisione di
Francesco Guatieri come principale Game Master.
    A partire dall'anno 2014 è passato sotto il controllo di Giovanni Mascellani e Giovanni Paolini. Nel 2014 sono state giocate due partite, una in primavera e una in autunno. Dopo la sesta edizione c'è stato un lungo periodo di pausa, per poi riprendere con la settima edizione nella primavera del 2017, gestita da Alessandro Iraci, Manuele Cusumano e Matteo Migliorini.
    </p>
    </div>
    {% include "games_list.html" with games=ongoing_games title="Partite in corso" %}
    {% include "games_list.html" with games=beginning_games title="Iscrizioni aperte" %}
    {% include "games_list.html" with games=ended_games title="Partite terminate" %}
</main>

{% endblock %}

templates/load_game.html
{% extends "base.html" %}

{% block content %}

<main id="content">
    <h1>Carica partita da file</h1>

    <div class="info-block">
        <p>Carica la partita da file JSON. <strong>Tutti i turni, gli eventi, e i giocatori di questa partita verranno eliminati.</strong></p>
        <p>
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Carica" /></p>
        </form>
        </p>
    </div>
</main>
{% endblock %}

templates/manage_masters.html
{% extends "base.html" %}

{% block content %}

<main id="content">
    <h1>Gestisci Game Master</h1>

    <div class="info-block">
        <div class="separator">
            <h2>Aggiungi o rimuovi un GM</h2>
        </div>
        I seguenti utenti sono master della partita in corso:

        <ul>
        {% for m in masters %}
        <li>
            <form method="post" action="{% url "game:deletemaster" game_name=game.name pk=m.pk %}">
            {% csrf_token %}
            <label>{{ m.user.username }} ({{ m.full_name }})</label><input type="submit" value="Elimina">
            </form>
        </li>
        {% endfor %}
        <li>
        <form method="post" action="">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Aggiungi">
        </form>
        </li>
        </ul>

        {% if message != None %}
            <p><strong>{{ message }}</strong></p>
        {% endif %}

        <form method="get" action="{% url "game:settings" game_name=game.name %}">
            <input type="submit" value="Indietro">
        </form>
    </div>


    </div>
</main>
{% endblock %}

templates/personal_info.html
{% extends "base_info.html" %}

{% block personal_info %}
    <h1>Informazioni personali</h1>

    <div class="info-block">
        <table class="normal">
            <tr><td>Nome</td><td>{{ player.full_name }}</td></tr>
            <tr><td>Fazione</td><td>{{ player.team_as_italian_string_property }}</td></tr>
            <tr><td>Ruolo</td><td>
                {{ player.role.name|default:"Nessuno" }}
            </td></tr>
            <tr><td>Aura</td><td>{{ player.aura_as_italian_string_property }}</td></tr>
            <tr><td>Stato</td><td>{{ player.status_as_italian_string_property }}</td></tr>
            <tr><td>Mistico</td><td>{{ player.is_mystic|yesno:"Sì,No,Boh" }}</td></tr>
            {% if player.specter %}
              <tr><td>Spettro</td><td>{{ player.specter | yesno:"Sì,No,Boh" }}</td></tr>
              <tr><td>Incantesimo</td><td>{{ player.dead_power.name }}</td></tr>
            {% endif %}
            {% if current_turn.phase == DAY %}
                <tr><td>Vota</td><td>{{ player.recorded_vote | default:"Nessuno" }}</td></tr>
                {% if display_mayor %}
                    <tr><td>Eleggi</td><td>{{ player.recorded_elect | default:"Nessuno" }}</td></tr>
                {% endif %}
            {% elif current_turn.phase == NIGHT %}
                <tr><td>Usa {{ player.alive|yesno:"abilità,potere" }} su</td><td>{{ player.role.recorded_target | default:"Nessuno" }}</td></tr>
            {% endif %}
        </table>

        {% if player.is_mayor %}
            <p>Sei l'attuale Sindaco del villaggio.</p>
        {% endif %}

    </div>

{% endblock %}

{% block events_title %}
    <h1>Eventi</h1>
{% endblock %}

templates/propositions.html
{% extends "base.html" %}

{% block content %}

<main id="content">
    <h1>Proposizioni Iniziali</h1>

    <div class="info-block">
        Fornirai al villaggio le seguenti proposizioni iniziali, di cui dovrai garantire la veridicità.

        <ul>
        {% for prop in propositions %}
        <li>
            <form method="post" action="{% url "game:deleteproposition" game_name=game.name pk=prop.pk %}">
            {% csrf_token %}
            <label>{{ prop.text }}</label><input type="submit" value="Elimina">
            </form>
        </li>
        {% endfor %}
        <li>
        <form method="post" action="">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Aggiungi">
        </form>
        </li>
        </ul>
        <form method="get" action="{% url "game:advanceturn" game_name=game.name %}">
            <input type="submit" value="Termina prologo" />
        </form>

        {% if message != None %}
            <p><strong>{{ message }}</strong></p>
        {% endif %}

    </div>
</main>
{% endblock %}

templates/public_info.html
{% extends "base_info.html" %}

{% block events_title %}
    <h1>Bacheca degli eventi</h1>
{% endblock %}

templates/seed.html
{% extends "base.html" %}

{% block content %}

<main id="content">
    <h1>Inizializza partita</h1>

    <div class="info-block">
        <p>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Conferma" /></p>
        </form>
        </p>

        {% if message != None %}
            <p><strong>{{ message }}</strong></p>
        {% endif %}

    </div>
</main>
{% endblock %}

templates/status.html
<h1>{{ game.title }}</h1>

<div class="info-block">

<div class="separator"><div class="separator"><h2>{{ current_turn.turn_as_italian_string_property }}</h2></div></div>

<p>
    {% if current_turn.phase == CREATION %}
        {% if is_master %}
            Hai creato con successo la partita. Una volta che i giocatori si sono uniti
            al villaggio, puoi selezionare "Setup iniziale" per configurare l'avvio della
            partita. In "Gestione partita" trovi alcuni utili parametri di configurazione,
            come la durata delle varie fasi e alcuni strumenti per gestire lo svolgimento
            della partita.
        {% elif not game.started %}
            {{ game.description }}
            {% if user.is_authenticated %}
            </p><p>
                {% if player %}
                    Sei iscritt{{ user.profile.oa }} a questa partita.
                {% else %}
                    Non sei iscritt{{ user.profile.oa }} a questa partita.
                {% endif %}
            {% endif %}
        {% endif %}
    {% endif %}
    {% if current_turn.phase == DAWN %}
        Un'alba {{ weather.adjective }}a sta sorgendo sul villaggio.
    {% endif %}
    
    {% if current_turn.phase == SUNSET %}
        Un {{ weather.adjective }}o tramonto sta calando sul villaggio.
    {% endif %}
    
    {% if current_turn.phase == DAY %}
        {% if weather.type == "clear" %}
            I cortili e le strade fremono di attività sotto il cielo terso e azzurro.
            Qua e là, gruppetti di persone parlottano furtivamente di quanto è accaduto nelle ultime notti.
        {% endif %}
        {% if weather.type == "cloudy" %}
            Sotto un cielo nuvoloso e grigio, le persone si affaccendano operose tra le strette stradicciole.
            Qualcuno si ferma a guardare la bacheca del villaggio, o a discutere brevemente degli avvenimenti più recenti, prima di tornare alla propria occupazione.
        {% endif %}
        {% if weather.type == "light rain" %}
            Una leggera pioggerellina cade tra le case e sui tetti.
            Alcuni si aggirano per le strade avvolti nei propri mantelli, per chissà quali loschi affari, ma i più preferiscono rimanere all'asciutto nelle proprie dimore.
        {% endif %}
        {% if weather.type == "heavy rain" %}
            Non c'è anima viva che si avventuri sotto la fitta pioggia che si abbatte sulle strade.
            Quelli che non sono al riparo delle proprie case si sono radunati nella locanda del villaggio, a bere e a discorrere delle ultime novità.
        {% endif %}
    {% endif %}
    
    {% if current_turn.phase == NIGHT %}
        {% if weather.type == "clear" %}
            Le stelle brillano nel sereno cielo notturno e la luna illumina le strade silenziose.
            Attraverso l'oscurità dei vicoli più angusti, si possono di tanto in tanto percepire dei cauti movimenti.
            Forse non tutti stanno dormendo, stanotte.
        {% endif %}
        {% if weather.type == "cloudy" %}
            La notte è resa più buia da fitte nubi che celano il chiarore della luna.
            Alcuni ne approfittano portando avanti le proprie losche attività; altri, invece, cercano di prendere sonno nella speranza di risvegliarsi di nuovo.
        {% endif %}
        {% if weather.type == "light rain" %}
            Una pioggia leggera rompe delicatamente il silenzio della notte.
            Ogni tanto si possono a malapena percepire anche dei passi frettolosi, ai quali l'oscurità impedisce di attribuire un nome.
        {% endif %}
        {% if weather.type == "heavy rain" %}
            Il rumore della pioggia battente copre quasi qualsiasi altro suono.
            Ma, attraverso l'oscurità impenetrabile, si possono talvolta distinguere degli ululati.
        {% endif %}
    {% endif %}
</p>

{% if display_mayor %}
    {% if game.mayor != None %}
        <p>Il Sindaco del villaggio è {{ game.mayor.full_name }}.</p>
    {% else %}
        <p>Il Sindaco del villaggio non è ancora stato eletto.
    {% endif %}
{% endif %}

{% if display_time %}
    {% if current_turn.end is not None %}
        {% if current_turn.phase == DAY %}
            <p>Il prossimo rogo sarà il {{ current_turn.end | date:"d/m" }} alle {{ current_turn.end | time:"H:i" }}.</p>
        {% endif %}
        {% if current_turn.phase == NIGHT %}
            <p>Il sole sorgerà alle ore {{ current_turn.end | time:"H:i" }}.</p>
        {% endif %}
    {% else %}
        {% if current_turn.phase == NIGHT %}
            <p>Stranamente non si riesce a prevedere a che ora sorgerà il sole.</p>
        {% endif %}
        {% if current_turn.phase == DAY %}
            <p>L'orario del prossimo rogo non è ancora stato deciso.</p>
        {% endif %}
        {% if current_turn.phase == DAWN %}
            <p>Sembra che il sole stia impiegando un tempo insolitamente lungo per sorgere.</p>
        {% endif %}
        {% if current_turn.phase == SUNSET %}
            <p>Sembra che il sole stia impiegando un tempo insolitamente lungo per tramontare.</p>
        {% endif %}
    {% endif %}
{% endif %}

</div>